import {
  CivilPDF,
  ContabilidadPDF,
  DesarrolloPDF,
  ElectricidadPDF,
  ElectronicaPDF,
  GestionPDF,
  MecanicaPDF,
  MecatronicaPDF,
} from "@/images";

const studyPlanDayNight = {
  duration: "Seis semestres equivalentes a tres años académicos.",
  dayShift: "8am a 1pm.",
  nightShift: "6pm a 10:20pm.",
};
const studyPlanNoDay = {
  duration: "Seis semestres equivalentes a tres años académicos.",
  nightShift: "6pm a 10:20pm.",
};
const studyPlanNoNight = {
  duration: "Seis semestres equivalentes a tres años académicos.",
  dayShift: "8am a 1pm.",
};

export const careersData = [
  {
    type: "civil-construction",
    title: "PROFESIONAL TÉCNICO EN CONSTRUCCIÓN CIVIL",
    perfil_egreso:
      "Supervisa información topográfica, elabora planos y modelamientos, administra recursos y actividades del proyecto, controla y dirige la obra e implementa sistemas de gestión de calidad, seguridad, salud y medio ambiente; actúa con ética, usa tecnologías de la información, promueve el emprendimiento, la cultura ambiental y el trabajo colaborativo.",
    competencia_general:
      "Planificar, organizar, ejecutar y controlar los trabajos de obras civiles, considerando criterios técnicos, de calidad y de seguridad, y optimizando el rendimiento de los recursos.",
    competencias_especificas: [
      "Supervisar la información topográfica.",
      "Elaborar planos, replanteos y modelamientos.",
      "Administrar información, recursos y actividades del proyecto.",
      "Controlar la ejecución de la obra.",
      "Dirigir las labores de los grupos de trabajo.",
      "Implementar sistemas de gestión de calidad, seguridad, salud y medio ambiente.",
    ],
    campos_accion: [
      "Empresas constructoras privadas",
      "Instituciones públicas del sector construcción",
      "Emprendimientos propios",
    ],
    puestos_trabajo: [
      "Gerente de Micro y Pequeña Empresa",
      "Supervisor de calidad de obras",
      "Supervisor de obras",
      "Asistente de gestión de recursos disponibles",
      "Topógrafo",
      "Dibujante CAD (AutoCAD, Civil3D, ArchiCAD)",
    ],
    salida_estudios: [
      "Ingeniería Civil",
      "Ingeniería Industrial",
      "Arquitectura",
      "Ingeniería Topográfica",
      "Docencia",
    ],
    studyPlan: studyPlanNoDay,
    curriculumMap: CivilPDF,
  },
  {
    type: "accounting",
    title: "PROFESIONAL TÉCNICO EN CONTABILIDAD",
    perfil_egreso:
      "Desarrolla y supervisa operaciones contables‑financieras, formula estados financieros y actualiza procedimientos contables conforme a la normativa; actúa éticamente, se comunica en español e inglés, usa TIC, emprende y lidera con conciencia ambiental.",
    competencia_general:
      "Planificar, organizar, verificar y registrar las operaciones económicas y financieras de entidades públicas y privadas de acuerdo con el sistema de contabilidad y la legislación vigente.",
    competencias_especificas: [
      "Desarrollar operaciones de contabilidad y finanzas.",
      "Supervisar operaciones de contabilidad y finanzas.",
      "Formular estados financieros.",
      "Actualizar procedimientos contables y financieros.",
    ],
    campos_accion: [
      "Empresas privadas del sector contable y financiero",
      "Instituciones públicas",
      "Emprendimientos propios",
    ],
    puestos_trabajo: [
      "Gerente de Micro y Pequeña Empresa",
      "Asesor contable de pequeña y microempresa",
      "Analista de costos y finanzas",
      "Asistente contable",
      "Jefe de área contable",
      "Docente en contabilidad",
    ],
    salida_estudios: [],
    studyPlan: studyPlanDayNight,
    curriculumMap: ContabilidadPDF,
  },
  {
    type: "information-systems",
    title: "PROFESIONAL TÉCNICO EN DESARROLLO DE SISTEMAS DE INFORMACION",
    perfil_egreso:
      "Desarrolla software multiplataforma, realiza pruebas integrales de sistemas TI y administra el diseño funcional de los sistemas; se comunica en español e inglés, usa tecnologías para la innovación, actúa éticamente y lidera proyectos.",
    competencia_general:
      "Planificar, implementar y gestionar el uso de tecnologías de información y comunicación en una organización, garantizando calidad, seguridad y ética, y fomentando el trabajo en equipo.",
    competencias_especificas: [
      "Desarrollar programas de sistemas de información.",
      "Realizar pruebas integrales de sistemas y servicios TI.",
      "Administrar el diseño funcional de sistemas de información.",
    ],
    campos_accion: [
      "Empresas privadas de tecnología",
      "Instituciones públicas",
      "Emprendimientos propios",
    ],
    puestos_trabajo: [
      "Gerente de Micro y Pequeña Empresa",
      "Jefe de soporte técnico",
      "Administrador de base de datos",
      "Diseñador gráfico, web y multimedia",
      "Técnico en redes",
      "Técnico en mantenimiento de equipos",
      "Programador de sistemas",
    ],
    salida_estudios: [
      "Ingeniería de Sistemas",
      "Ingeniería en Computación e Informática",
      "Ingeniería Informática",
      "Comercio Electrónico",
      "Ingeniería Estadística e Informática",
      "Ingeniería de Software",
    ],
    studyPlan: studyPlanDayNight,
    curriculumMap: DesarrolloPDF,
  },
  {
    type: "electricity",
    title: "PROFESIONAL TÉCNICO EN ELECTRICIDAD INDUSTRIAL",
    perfil_egreso: "",
    competencia_general:
      "Planificar, organizar, proyectar, supervisar y ejecutar el montaje, instalación, mantenimiento y automatización de sistemas eléctricos, cumpliendo normas de seguridad y calidad.",
    competencias_especificas: [],
    campos_accion: [
      "Empresas industriales",
      "Instituciones públicas",
      "Emprendimientos propios",
    ],
    puestos_trabajo: [
      "Gerente de Micro y Pequeña Empresa",
      "Jefe de soporte técnico",
      "Supervisor de planta",
    ],
    salida_estudios: [
      "Ingeniería Eléctrica",
      "Ingeniería Mecánica‑Eléctrica",
      "Ingeniería Electrónica",
      "Ingeniería Industrial",
    ],
    studyPlan: studyPlanDayNight,
    curriculumMap: ElectricidadPDF,
  },
  {
    type: "electronics",
    title: "PROFESIONAL TÉCNICO EN ELECTRÓNICA INDUSTRIAL",
    perfil_egreso: "",
    competencia_general:
      "Planificar, organizar, diseñar, supervisar y ejecutar la construcción, montaje, instalación y mantenimiento de sistemas electrónicos de control de procesos industriales, aplicando normas de calidad, seguridad y cuidado ambiental.",
    competencias_especificas: [],
    campos_accion: [
      "Aplicaciones industriales",
      "Plantas industriales",
      "Laboratorios",
      "Talleres",
      "Instituciones educativas",
    ],
    puestos_trabajo: [
      "Supervisor de plantas con sistemas eléctricos",
      "Instructor",
      "Especialista en sistemas electrónicos automatizados",
    ],
    salida_estudios: [
      "Ingeniería de Sistemas",
      "Ingeniería Mecatrónica",
      "Ingeniería Electrónica",
      "Ingeniería Industrial",
    ],
    studyPlan: studyPlanDayNight,
    curriculumMap: ElectronicaPDF,
  },
  {
    type: "administrative-management",
    title: "PROFESIONAL TÉCNICO EN GESTIÓN ADMINISTRATIVA",
    perfil_egreso:
      "Elabora procedimientos administrativos, define presupuestos, administra recursos humanos, materiales y financieros, y supervisa el plan operativo; se comunica eficazmente, usa TIC, emprende, cuida el ambiente y lidera con innovación.",
    competencia_general:
      "Planificar, organizar, dirigir y controlar los procesos administrativos de una organización.",
    competencias_especificas: [
      "Elaborar procedimientos administrativos.",
      "Definir presupuestos del plan de actividades.",
      "Contratar servicios especializados.",
      "Administrar recursos humanos, materiales y financieros.",
      "Supervisar el cumplimiento del plan operativo.",
    ],
    campos_accion: [
      "Administración",
      "Logística",
      "Recursos Humanos",
      "Proyectos Empresariales",
      "Marketing",
      "Costos y Presupuestos",
      "Operaciones",
      "Comercio Exterior",
      "Créditos y Cobranzas",
      "Finanzas",
      "Contabilidad",
      "Trámite Documentario",
      "Atención al Cliente",
      "Emprendimiento",
      "Asesoría Empresarial",
    ],
    puestos_trabajo: [
      "Administrador de personal",
      "Analista de créditos y cobranzas",
      "Técnico en control de producción",
      "Analista en comercio exterior",
      "Técnico en logística",
      "Supervisor de organización",
      "Analista en personal",
      "Administrador de gestión financiera",
      "Analista de información general",
    ],
    salida_estudios: [
      "Licenciatura en Administración",
      "Asistente Administrativo",
      "Docencia",
      "Ingeniería Administrativa",
    ],
    studyPlan: studyPlanDayNight,
    curriculumMap: GestionPDF,
  },
  {
    type: "mechanics",
    title: "PROFESIONAL TÉCNICO EN MECÁNICA DE PRODUCCIÓN INDUSTRIAL",
    perfil_egreso: "",
    competencia_general:
      "Planificar, coordinar, supervisar y evaluar labores productivas y de mantenimiento mecánico en plantas industriales; diseñar, fabricar y reconstruir elementos de máquinas y matrices, cumpliendo normas técnicas y de seguridad.",
    competencias_especificas: [],
    campos_accion: [
      "Plantas industriales",
      "Maestranzas",
      "Factorías",
      "Talleres",
      "Instituciones educativas",
    ],
    puestos_trabajo: [
      "Supervisor de planta metal‑mecánica",
      "Diseñador de procesos de fabricación",
      "Operador de máquinas‑herramientas",
      "Gerente de Micro y Pequeña Empresa",
    ],
    salida_estudios: [
      "Ingeniería Química",
      "Ingeniería Mecánica",
      "Ingeniería Industrial",
      "Ingeniería Metalurgia",
      "Ingeniería Mecatrónica",
      "Especialista en Mantenimiento",
    ],
    studyPlan: studyPlanDayNight,
    curriculumMap: MecanicaPDF,
  },
  {
    type: "mechatronics",
    title: "PROFESIONAL TÉCNICO EN MECATRONICA AUTOMOTRIZ",
    perfil_egreso:
      "Realiza mantenimiento programado y reparación de sistemas automotrices convencionales y con asistencia electrónica, incluidas suspensión, dirección, frenos, sistemas eléctricos, transmisión y motor; puede convertir sistemas de combustible; actúa con ética, comunica en español e inglés, usa TIC, emprende y lidera con enfoque ambiental.",
    competencia_general:
      "Planificar, organizar, proyectar y supervisar el mantenimiento integral de unidades automotrices, aplicando normas de seguridad industrial, control de calidad y preservación ambiental.",
    competencias_especificas: [],
    campos_accion: [
      "Empresas privadas del sector automotriz",
      "Instituciones públicas",
      "Talleres propios",
    ],
    puestos_trabajo: [
      "Jefe de taller",
      "Especialista en instalaciones eléctricas",
      "Reparación de motor",
      "Reparación de motor de arranque/generador/alternador",
      "Alineamiento de dirección",
      "Caja de cambio y transmisión",
      "Frenos",
      "Rectificador de motores",
      "Calefacción y aire acondicionado",
      "Laboratorio diésel",
      "Supervisor de planta metal‑mecánica",
      "Afinamiento electrónico diésel",
      "Operador de máquinas‑herramientas",
      "Afinamiento electrónico gasolina",
      "Diseñador de procesos de fabricación",
      "Gerente de Micro y Pequeña Empresa",
    ],
    salida_estudios: [
      "Educación",
      "Ingeniería Mecatrónica",
      "Especialista en Mantenimiento",
      "Ingeniería Mecánica",
      "Ingeniería Industrial",
      "Ingeniería Metalurgia",
      "Ingeniería en Mantenimiento",
    ],
    studyPlan: studyPlanNoNight,
    curriculumMap: MecatronicaPDF,
  },
];
