import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faChevronDown,
  faBook,
  faUser,
  faSchool,
  faEnvelope,
  faFileAlt,
  faGlobe,
  faFlask,
  faBullhorn,
  faLaptopCode,
  faUserGraduate,
  faCalendarAlt,
  faBookOpen,
  faLaptop,
  faSearch,
  faPhone,
  faMapMarkerAlt,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faChevronDown,
  faBook,
  faUser,
  faSchool,
  faEnvelope,
  faFileAlt,
  faGlobe,
  faFlask,
  faBullhorn,
  faLaptopCode,
  faUserGraduate,
  faCalendarAlt,
  faBookOpen,
  faLaptop,
  faSearch,
  faPhone,
  faEnvelope,
  faMapMarkerAlt,
);
